// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/qrcode.proto

package qrcode

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Qrcode service

func NewQrcodeEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Qrcode service

type QrcodeService interface {
	GetQrcode(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Qrcode_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Qrcode_PingPongService, error)
}

type qrcodeService struct {
	c    client.Client
	name string
}

func NewQrcodeService(name string, c client.Client) QrcodeService {
	return &qrcodeService{
		c:    c,
		name: name,
	}
}

func (c *qrcodeService) GetQrcode(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Qrcode.GetQrcode", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qrcodeService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Qrcode_StreamService, error) {
	req := c.c.NewRequest(c.name, "Qrcode.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &qrcodeServiceStream{stream}, nil
}

type Qrcode_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type qrcodeServiceStream struct {
	stream client.Stream
}

func (x *qrcodeServiceStream) Close() error {
	return x.stream.Close()
}

func (x *qrcodeServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *qrcodeServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *qrcodeServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *qrcodeServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *qrcodeService) PingPong(ctx context.Context, opts ...client.CallOption) (Qrcode_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Qrcode.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &qrcodeServicePingPong{stream}, nil
}

type Qrcode_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type qrcodeServicePingPong struct {
	stream client.Stream
}

func (x *qrcodeServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *qrcodeServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *qrcodeServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *qrcodeServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *qrcodeServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *qrcodeServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Qrcode service

type QrcodeHandler interface {
	GetQrcode(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Qrcode_StreamStream) error
	PingPong(context.Context, Qrcode_PingPongStream) error
}

func RegisterQrcodeHandler(s server.Server, hdlr QrcodeHandler, opts ...server.HandlerOption) error {
	type qrcode interface {
		GetQrcode(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Qrcode struct {
		qrcode
	}
	h := &qrcodeHandler{hdlr}
	return s.Handle(s.NewHandler(&Qrcode{h}, opts...))
}

type qrcodeHandler struct {
	QrcodeHandler
}

func (h *qrcodeHandler) GetQrcode(ctx context.Context, in *Request, out *Response) error {
	return h.QrcodeHandler.GetQrcode(ctx, in, out)
}

func (h *qrcodeHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.QrcodeHandler.Stream(ctx, m, &qrcodeStreamStream{stream})
}

type Qrcode_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type qrcodeStreamStream struct {
	stream server.Stream
}

func (x *qrcodeStreamStream) Close() error {
	return x.stream.Close()
}

func (x *qrcodeStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *qrcodeStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *qrcodeStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *qrcodeStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *qrcodeHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.QrcodeHandler.PingPong(ctx, &qrcodePingPongStream{stream})
}

type Qrcode_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type qrcodePingPongStream struct {
	stream server.Stream
}

func (x *qrcodePingPongStream) Close() error {
	return x.stream.Close()
}

func (x *qrcodePingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *qrcodePingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *qrcodePingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *qrcodePingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *qrcodePingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
